// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dashboard: typeof import('./../views/dashboard/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Login: typeof import('./../views/login/index.vue')['default']
    LoginAction: typeof import('./../views/login/cpns/login-action.vue')['default']
    LoginView: typeof import('./../views/login/cpns/login-view.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./../views/login/cpns/sign-in.vue')['default']
    SignUp: typeof import('./../views/login/cpns/sign-up.vue')['default']
  }
}
